version: '3'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=geo
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=geodjango

volumes:
  postgres_data:


# Для запуска включить SQL_HOST в settings.py (=db)

#Чтобы сделать дамп существующей базы ввести команду:
# pg_dump -U user db_name > db_filename.sql

# Для загрузки дампа базы в контейнер не запускать миграции и ввести команду:
# docker exec -i container_name(db) psql --username pg_username db_name </path/on/your/machine/dump.sql